### ISSUE TITLE
styled components

### ISSUE THREAD

**Issue by ealmiladi** [SmartBear/react-gherkin-editor#161]
Why are styled-components included as a devDependency? Running into issues where I have to install styled-components locally in order for everything to compile correctly.

**Comment by mcoqblin-hiptest** [comment]
Hello,

The styled-components package is included as a peer dependency because it is required by react-gherkin-editor (we are using it as part of the editor design), but should only exist once and as a single version in your project, like React.

A peer dependency means react-gherkin-editor will not install the package for you, as you could already have it, but you do have to specify it in your package file.

Since react-gherkin-editor is not making a heavy usage of it I think it should be interesting to remove this dependency.
